# -*- coding: utf-8 -*-
"""TelcoCustomerChurn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yulhWpiQ_MY5OqxYCDDY7PjvvMvE5BHH
"""

# !unzip TelcoCustomerChurn.zip

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

df = pd.read_csv('Telco-Customer-Churn.csv')
df.head()

"""### Explanation of Columns

| Column Name | Description |
| :--- | :--- |
| **customerID** | A unique ID that identifies each individual customer. |
| **gender** | Whether the customer is a male or a female. |
| **SeniorCitizen** | Indicates if the customer is a senior citizen (1: Yes, 0: No). |
| **Partner** | Whether the customer has a partner (Yes, No). |
| **Dependents** | Whether the customer has dependents (Yes, No). |
| **tenure** | Number of months the customer has stayed with the company. |
| **PhoneService** | Whether the customer has a phone service (Yes, No). |
| **MultipleLines** | Whether the customer has multiple lines (Yes, No, No phone service). |
| **InternetService** | Customer’s internet service provider (DSL, Fiber optic, No). |
| **OnlineSecurity** | Whether the customer has online security (Yes, No, No internet service). |
| **OnlineBackup** | Whether the customer has online backup (Yes, No, No internet service). |
| **DeviceProtection** | Whether the customer has device protection (Yes, No, No internet service). |
| **TechSupport** | Whether the customer has tech support (Yes, No, No internet service). |
| **StreamingTV** | Whether the customer has streaming TV (Yes, No, No internet service). |
| **StreamingMovies** | Whether the customer has streaming movies (Yes, No, No internet service). |
| **Contract** | The contract term of the customer (Month-to-month, One year, Two year). |
| **PaperlessBilling** | Whether the customer has paperless billing (Yes, No). |
| **PaymentMethod** | The customer’s payment method (Electronic check, Mailed check, Bank transfer, Credit card). |
| **MonthlyCharges** | The amount charged to the customer monthly. |
| **TotalCharges** | The total amount charged to the customer. |
| **Churn** | **Target Variable**: Whether the customer churned (left the company) or not (Yes or No). |
"""

df.columns

df = df.drop(['customerID', 'gender'], axis=1)

df.columns

df.info()

# Convert TotalCharges to numeric
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

# Check for any new null values created during conversion
print(f"Missing values in TotalCharges: {df['TotalCharges'].isnull().sum()}")

# Verify the new data type
print(df['TotalCharges'].dtype)

print(len(df))

df.isna().sum()

df = df.dropna()

df.isna().sum()

df.describe()

"""### Step 1: Binary Encoding
We'll map 'Yes' to 1 and 'No' (including variants like 'No internet service') to 0 for binary features.
"""

import pandas as pd

# Strictly binary columns (only Yes/No)
binary_cols = ['Partner', 'Dependents', 'PhoneService', 'PaperlessBilling', 'Churn']

# Columns that have 'No internet service' or 'No phone service' as a distinct third category
service_detail_cols = ['MultipleLines', 'OnlineSecurity', 'OnlineBackup',
                       'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies']

# Standard categorical columns
multi_class_cols = ['InternetService', 'Contract', 'PaymentMethod']

# 1. Map strictly binary columns to 0/1
for col in binary_cols:
    df[col] = df[col].replace({'Yes': 1, 'No': 0}).astype(int)

# 2. Use One-Hot Encoding for everything else, explicitly setting dtype to int
cols_to_encode = service_detail_cols + multi_class_cols
df = pd.get_dummies(data=df, columns=cols_to_encode, dtype=int)

print(f"New shape of dataframe: {df.shape}")
display(df.head())

"""### Data Ready for Modeling
The categorical variables have been encoded while preserving the distinction between 'No' and 'No Service'. The dataset is now numerically encoded.
"""

# Final check of the encoded features
print(f"Total columns: {len(df.columns)}")
print("Sample of new service-specific columns:")
display(df.filter(like='No internet service').head())

"""### Scaling Numerical Features
We use `StandardScaler` to normalize the numerical columns ('tenure', 'MonthlyCharges', 'TotalCharges') so they have a mean of 0 and a standard deviation of 1.

### What is StandardScaler?

**StandardScaler** is a preprocessing technique used to standardize features by:
1.  **Centering**: Subtracting the mean of each feature so it becomes 0.
2.  **Scaling**: Dividing by the standard deviation so the feature has a unit variance (1).

**Why is it used?**
*   **Prevents Bias**: Algorithms like Logistic Regression, SVM, and KNN are sensitive to the magnitude of numbers. Scaling prevents features with large values (like `TotalCharges`) from dominating those with smaller values (like `tenure`).
*   **Faster Convergence**: Gradient-based optimizers (used in Neural Networks) converge much faster when features are on a similar scale.
"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
num_cols = ['tenure', 'MonthlyCharges', 'TotalCharges']

# Scale the numerical columns
df[num_cols] = scaler.fit_transform(df[num_cols])

print("Numerical columns scaled successfully.")
display(df[num_cols].head())

x = df.drop(['Churn'], axis=1)
y = df['Churn']

# Fixing the assignment order: X_train, X_test, y_train, y_test
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb

# Using Classifiers instead of Regressors
log_reg = LogisticRegression(max_iter=1000)
rf_clf = RandomForestClassifier(n_estimators=100, random_state=42)
xgb_clf = xgb.XGBClassifier(use_label_encoder=False, eval_metric='logloss')

# Fit models
log_reg.fit(x_train, y_train)
rf_clf.fit(x_train, y_train)
xgb_clf.fit(x_train, y_train)

print("Classification models trained successfully!")

from sklearn.metrics import accuracy_score

# Evaluate Accuracy
models = {
    "Logistic Regression": log_reg,
    "Random Forest Classifier": rf_clf,
    "XGBoost Classifier": xgb_clf
}

for name, model in models.items():
    train_acc = accuracy_score(y_train, model.predict(x_train))
    test_acc = accuracy_score(y_test, model.predict(x_test))
    print(f"{name}:")
    print(f"  Training Accuracy: {train_acc:.4f}")
    print(f"  Testing Accuracy:  {test_acc:.4f}\n")

"""### Improving Generalization with Regularization
To fix the overfitting (high training accuracy vs. lower testing accuracy), we will tune the models by limiting their complexity. We will also use Cross-Validation for a more robust evaluation.
"""

from sklearn.model_selection import cross_val_score
from sklearn.metrics import roc_auc_score

# Retrain with regularization (e.g., max_depth)
log_reg_optimized = LogisticRegression(max_iter=1000, C=0.1)
rf_clf_optimized = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)
xgb_clf_optimized = xgb.XGBClassifier(n_estimators=100, max_depth=3, learning_rate=0.1, eval_metric='logloss')

# Evaluate with 5-fold Cross-Validation using ROC-AUC
models_opt = {
    "Tuned Logistic Regression": log_reg_optimized,
    "Tuned Random Forest": rf_clf_optimized,
    "Tuned XGBoost": xgb_clf_optimized
}

print("Model Performance (ROC-AUC Score):")
for name, model in models_opt.items():
    # Using 'roc_auc' as the scoring parameter
    cv_auc_scores = cross_val_score(model, x, y, cv=5, scoring='roc_auc')
    print(f"{name} CV ROC-AUC: {cv_auc_scores.mean():.4f} (+/- {cv_auc_scores.std() * 2:.4f})")

# Fit the best performer for final validation
rf_clf_optimized.fit(x_train, y_train)
# Predict probabilities for AUC calculation
train_probs = rf_clf_optimized.predict_proba(x_train)[:, 1]
test_probs = rf_clf_optimized.predict_proba(x_test)[:, 1]

print(f"\nOptimized RF Training ROC-AUC: {roc_auc_score(y_train, train_probs):.4f}")
print(f"Optimized RF Testing ROC-AUC: {roc_auc_score(y_test, test_probs):.4f}")

"""### Confusion Matrix Visualization
The confusion matrix shows the counts of true positives, true negatives, false positives, and false negatives, giving us a deeper look into model performance beyond just the ROC-AUC score.
"""

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Ensure models are fitted
log_reg_optimized.fit(x_train, y_train)
rf_clf_optimized.fit(x_train, y_train)
xgb_clf_optimized.fit(x_train, y_train)

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

models_list = [
    ("Logistic Regression", log_reg_optimized),
    ("Random Forest", rf_clf_optimized),
    ("XGBoost", xgb_clf_optimized)
]

# Using 'Positive' for Churn and 'Negative' for No Churn as requested
labels = ['Negative', 'Positive']

for i, (name, model) in enumerate(models_list):
    y_pred = model.predict(x_test)
    cm = confusion_matrix(y_test, y_pred)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=labels)
    disp.plot(ax=axes[i], cmap='Blues', values_format='d')
    axes[i].set_title(f"{name}\n(Pos=Churn, Neg=No Churn)")

plt.tight_layout()
plt.show()